// This file is @generated by prost-build.
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MidImConfig {
    ///
    #[prost(message, optional, tag = "1")]
    pub can_airdrop_to_im: ::core::option::Option<super::super::BoolValue>,
}
