// This file is @generated by prost-build.
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdInfo {
    ///
    #[prost(int64, tag = "1")]
    pub creative_id: i64,
    ///
    #[prost(int32, tag = "2")]
    pub creative_type: i32,
    ///
    #[prost(int32, tag = "3")]
    pub card_type: i32,
    ///
    #[prost(message, optional, tag = "4")]
    pub creative_content: ::core::option::Option<CreativeContent>,
    ///
    #[prost(string, tag = "5")]
    pub ad_cb: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "6")]
    pub resource: i64,
    ///
    #[prost(int32, tag = "7")]
    pub source: i32,
    ///
    #[prost(string, tag = "8")]
    pub request_id: ::prost::alloc::string::String,
    ///
    #[prost(bool, tag = "9")]
    pub is_ad: bool,
    ///
    #[prost(int64, tag = "10")]
    pub cm_mark: i64,
    ///
    #[prost(int32, tag = "11")]
    pub index: i32,
    ///
    #[prost(bool, tag = "12")]
    pub is_ad_loc: bool,
    ///
    #[prost(int32, tag = "13")]
    pub card_index: i32,
    ///
    #[prost(string, tag = "14")]
    pub client_ip: ::prost::alloc::string::String,
    ///
    #[prost(bytes = "vec", tag = "15")]
    pub extra: ::prost::alloc::vec::Vec<u8>,
    ///
    #[prost(int32, tag = "16")]
    pub creative_style: i32,
    ///
    #[prost(int64, tag = "17")]
    pub nature_ad: i64,
    ///
    #[prost(int32, tag = "18")]
    pub content_fast_access: i32,
}
impl ::prost::Name for AdInfo {
    const NAME: &'static str = "AdInfo";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.AdInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.AdInfo".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Args {
    ///
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    ///
    #[prost(int64, tag = "2")]
    pub up_id: i64,
    ///
    #[prost(string, tag = "3")]
    pub up_name: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "4")]
    pub rid: i32,
    ///
    #[prost(string, tag = "5")]
    pub rname: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "6")]
    pub tid: i64,
    ///
    #[prost(string, tag = "7")]
    pub tname: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "8")]
    pub track_id: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "9")]
    pub state: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "10")]
    pub converge_type: i32,
    ///
    #[prost(int64, tag = "11")]
    pub aid: i64,
}
impl ::prost::Name for Args {
    const NAME: &'static str = "Args";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.Args".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.Args".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Avatar {
    ///
    #[prost(string, tag = "1")]
    pub cover: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub uri: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "4")]
    pub r#type: i32,
    ///
    #[prost(string, tag = "5")]
    pub event: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub event_v2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "7")]
    pub defalut_cover: i32,
}
impl ::prost::Name for Avatar {
    const NAME: &'static str = "Avatar";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.Avatar".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.Avatar".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Base {
    ///
    #[prost(string, tag = "1")]
    pub card_type: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub card_goto: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub goto: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub param: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub cover: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub uri: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "8")]
    pub three_point: ::core::option::Option<ThreePoint>,
    ///
    #[prost(message, optional, tag = "9")]
    pub args: ::core::option::Option<Args>,
    ///
    #[prost(message, optional, tag = "10")]
    pub player_args: ::core::option::Option<PlayerArgs>,
    ///
    #[prost(int64, tag = "11")]
    pub idx: i64,
    ///
    #[prost(message, optional, tag = "12")]
    pub ad_info: ::core::option::Option<AdInfo>,
    ///
    #[prost(message, optional, tag = "13")]
    pub mask: ::core::option::Option<Mask>,
    ///
    #[prost(string, tag = "14")]
    pub from_type: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "15")]
    pub three_point_v2: ::prost::alloc::vec::Vec<ThreePointV2>,
    ///
    #[prost(message, repeated, tag = "16")]
    pub three_point_v3: ::prost::alloc::vec::Vec<ThreePointV3>,
    ///
    #[prost(message, optional, tag = "17")]
    pub desc_button: ::core::option::Option<Button>,
    ///
    #[prost(message, optional, tag = "18")]
    pub three_point_v4: ::core::option::Option<ThreePointV4>,
    ///
    #[prost(message, optional, tag = "19")]
    pub up_args: ::core::option::Option<UpArgs>,
}
impl ::prost::Name for Base {
    const NAME: &'static str = "Base";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.Base".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.Base".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Bubble {
    ///
    #[prost(string, tag = "1")]
    pub bubble_content: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "2")]
    pub version: i32,
    ///
    #[prost(int64, tag = "3")]
    pub stime: i64,
}
impl ::prost::Name for Bubble {
    const NAME: &'static str = "Bubble";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.Bubble".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.Bubble".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Button {
    ///
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub param: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub uri: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub event: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "5")]
    pub selected: i32,
    ///
    #[prost(int32, tag = "6")]
    pub r#type: i32,
    ///
    #[prost(string, tag = "7")]
    pub event_v2: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "8")]
    pub relation: ::core::option::Option<Relation>,
}
impl ::prost::Name for Button {
    const NAME: &'static str = "Button";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.Button".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.Button".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Card {
    ///
    #[prost(oneof = "card::Item", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12")]
    pub item: ::core::option::Option<card::Item>,
}
/// Nested message and enum types in `Card`.
pub mod card {
    ///
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Item {
        ///
        #[prost(message, tag = "1")]
        SmallCoverV5(::prost::alloc::boxed::Box<super::SmallCoverV5>),
        ///
        #[prost(message, tag = "2")]
        LargeCoverV1(::prost::alloc::boxed::Box<super::LargeCoverV1>),
        ///
        #[prost(message, tag = "3")]
        ThreeItemAllV2(::prost::alloc::boxed::Box<super::ThreeItemAllV2>),
        ///
        #[prost(message, tag = "4")]
        ThreeItemV1(::prost::alloc::boxed::Box<super::ThreeItemV1>),
        ///
        #[prost(message, tag = "5")]
        HotTopic(::prost::alloc::boxed::Box<super::HotTopic>),
        ///
        #[prost(message, tag = "6")]
        ThreeItemHV5(::prost::alloc::boxed::Box<super::DynamicHot>),
        ///
        #[prost(message, tag = "7")]
        MiddleCoverV3(::prost::alloc::boxed::Box<super::MiddleCoverV3>),
        ///
        #[prost(message, tag = "8")]
        LargeCoverV4(::prost::alloc::boxed::Box<super::LargeCoverV4>),
        ///
        #[prost(message, tag = "9")]
        PopularTopEntrance(::prost::alloc::boxed::Box<super::PopularTopEntrance>),
        ///
        #[prost(message, tag = "10")]
        RcmdOneItem(::prost::alloc::boxed::Box<super::RcmdOneItem>),
        ///
        #[prost(message, tag = "11")]
        SmallCoverV5Ad(::prost::alloc::boxed::Box<super::SmallCoverV5Ad>),
        ///
        #[prost(message, tag = "12")]
        TopicList(::prost::alloc::boxed::Box<super::TopicList>),
    }
}
impl ::prost::Name for Card {
    const NAME: &'static str = "Card";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.Card".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.Card".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreativeContent {
    ///
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "3")]
    pub video_id: i64,
    ///
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub image_url: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub image_md5: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub log_url: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "8")]
    pub log_md5: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "9")]
    pub url: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "10")]
    pub click_url: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "11")]
    pub show_url: ::prost::alloc::string::String,
}
impl ::prost::Name for CreativeContent {
    const NAME: &'static str = "CreativeContent";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.CreativeContent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.CreativeContent".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DislikeReason {
    ///
    #[prost(int64, tag = "1")]
    pub id: i64,
    ///
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
impl ::prost::Name for DislikeReason {
    const NAME: &'static str = "DislikeReason";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.DislikeReason".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.DislikeReason".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DoubleCards {
    ///
    #[prost(oneof = "double_cards::Card", tags = "1, 2, 3")]
    pub card: ::core::option::Option<double_cards::Card>,
}
/// Nested message and enum types in `DoubleCards`.
pub mod double_cards {
    ///
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Card {
        ///
        #[prost(message, tag = "1")]
        SmallCoverV2(::prost::alloc::boxed::Box<super::SmallCoverV2>),
        ///
        #[prost(message, tag = "2")]
        OnePicV2(::prost::alloc::boxed::Box<super::OnePicV2>),
        ///
        #[prost(message, tag = "3")]
        ThreePicV2(::prost::alloc::boxed::Box<super::ThreePicV2>),
    }
}
impl ::prost::Name for DoubleCards {
    const NAME: &'static str = "DoubleCards";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.DoubleCards".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.DoubleCards".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DynamicHot {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub top_left_title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub desc1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub desc2: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub more_uri: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub more_text: ::prost::alloc::string::String,
    ///
    #[prost(string, repeated, tag = "7")]
    pub covers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    ///
    #[prost(string, tag = "8")]
    pub cover_right_text: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "9")]
    pub top_rcmd_reason_style: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for DynamicHot {
    const NAME: &'static str = "DynamicHot";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.DynamicHot".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.DynamicHot".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EntranceItem {
    ///
    #[prost(string, tag = "1")]
    pub goto: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub icon: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub module_id: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub uri: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "6")]
    pub entrance_id: i64,
    ///
    #[prost(message, optional, tag = "7")]
    pub bubble: ::core::option::Option<Bubble>,
    ///
    #[prost(int32, tag = "8")]
    pub entrance_type: i32,
}
impl ::prost::Name for EntranceItem {
    const NAME: &'static str = "EntranceItem";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.EntranceItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.EntranceItem".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionalButton {
    ///
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    ///
    #[prost(message, repeated, tag = "2")]
    pub button_metas: ::prost::alloc::vec::Vec<FunctionalButtonMeta>,
}
impl ::prost::Name for FunctionalButton {
    const NAME: &'static str = "FunctionalButton";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.FunctionalButton".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.FunctionalButton".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionalButtonMeta {
    ///
    #[prost(string, tag = "1")]
    pub icon: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub button_status: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub toast: ::prost::alloc::string::String,
}
impl ::prost::Name for FunctionalButtonMeta {
    const NAME: &'static str = "FunctionalButtonMeta";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.FunctionalButtonMeta".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.FunctionalButtonMeta".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HotTopic {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<HotTopicItem>,
}
impl ::prost::Name for HotTopic {
    const NAME: &'static str = "HotTopic";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.HotTopic".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.HotTopic".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HotTopicItem {
    ///
    #[prost(string, tag = "1")]
    pub cover: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub uri: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub param: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
}
impl ::prost::Name for HotTopicItem {
    const NAME: &'static str = "HotTopicItem";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.HotTopicItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.HotTopicItem".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HotwordEntrance {
    ///
    #[prost(int64, tag = "1")]
    pub hotword_id: i64,
    ///
    #[prost(string, tag = "2")]
    pub hot_text: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub h5_url: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub icon: ::prost::alloc::string::String,
}
impl ::prost::Name for HotwordEntrance {
    const NAME: &'static str = "HotwordEntrance";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.HotwordEntrance".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.HotwordEntrance".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InlineProgressBar {
    ///
    #[prost(string, tag = "1")]
    pub icon_drag: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub icon_drag_hash: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub icon_stop: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub icon_stop_hash: ::prost::alloc::string::String,
}
impl ::prost::Name for InlineProgressBar {
    const NAME: &'static str = "InlineProgressBar";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.InlineProgressBar".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.InlineProgressBar".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LargeCoverV1 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_gif: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "3")]
    pub avatar: ::core::option::Option<Avatar>,
    ///
    #[prost(string, tag = "4")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub cover_left_text3: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub cover_badge: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "8")]
    pub top_rcmd_reason: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "9")]
    pub bottom_rcmd_reason: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "10")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "11")]
    pub official_icon: i32,
    ///
    #[prost(int32, tag = "12")]
    pub can_play: i32,
    ///
    #[prost(message, optional, tag = "13")]
    pub top_rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "14")]
    pub bottom_rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "15")]
    pub rcmd_reason_style_v2: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "16")]
    pub left_cover_badge_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "17")]
    pub right_cover_badge_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(string, tag = "18")]
    pub cover_badge2: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "19")]
    pub like_button: ::core::option::Option<LikeButton>,
    ///
    #[prost(int32, tag = "20")]
    pub title_single_line: i32,
    ///
    #[prost(string, tag = "21")]
    pub cover_right_text: ::prost::alloc::string::String,
}
impl ::prost::Name for LargeCoverV1 {
    const NAME: &'static str = "LargeCoverV1";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.LargeCoverV1".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.LargeCoverV1".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LargeCoverV2 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(message, optional, tag = "2")]
    pub avatar: ::core::option::Option<Avatar>,
    ///
    #[prost(string, tag = "3")]
    pub badge: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "4")]
    pub cover_right_button: ::core::option::Option<Button>,
    ///
    #[prost(string, tag = "5")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "6")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "7")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "8")]
    pub cover_left_icon2: i32,
    ///
    #[prost(string, tag = "9")]
    pub rcmd_reason: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "10")]
    pub official_icon: i32,
    ///
    #[prost(int32, tag = "11")]
    pub can_play: i32,
    ///
    #[prost(message, optional, tag = "12")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(int32, tag = "13")]
    pub show_top: i32,
    ///
    #[prost(int32, tag = "14")]
    pub show_bottom: i32,
}
impl ::prost::Name for LargeCoverV2 {
    const NAME: &'static str = "LargeCoverV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.LargeCoverV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.LargeCoverV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LargeCoverV3 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_gif: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "3")]
    pub avatar: ::core::option::Option<Avatar>,
    ///
    #[prost(message, optional, tag = "4")]
    pub top_rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "5")]
    pub bottom_rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(string, tag = "6")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "7")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "8")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "9")]
    pub cover_left_icon2: i32,
    ///
    #[prost(string, tag = "10")]
    pub cover_right_text: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "11")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "12")]
    pub official_icon: i32,
}
impl ::prost::Name for LargeCoverV3 {
    const NAME: &'static str = "LargeCoverV3";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.LargeCoverV3".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.LargeCoverV3".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LargeCoverV4 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub cover_left_text3: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub cover_badge: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "6")]
    pub can_play: i32,
    ///
    #[prost(message, optional, tag = "7")]
    pub up: ::core::option::Option<Up>,
    ///
    #[prost(string, tag = "8")]
    pub short_link: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "9")]
    pub share_subtitle: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "10")]
    pub play_number: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "11")]
    pub bvid: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "12")]
    pub sub_param: ::prost::alloc::string::String,
}
impl ::prost::Name for LargeCoverV4 {
    const NAME: &'static str = "LargeCoverV4";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.LargeCoverV4".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.LargeCoverV4".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LikeButton {
    ///
    #[prost(int64, tag = "1")]
    pub aid: i64,
    ///
    #[prost(int32, tag = "2")]
    pub count: i32,
    ///
    #[prost(bool, tag = "3")]
    pub show_count: bool,
    ///
    #[prost(string, tag = "4")]
    pub event: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "5")]
    pub selected: i32,
    ///
    #[prost(string, tag = "6")]
    pub event_v2: ::prost::alloc::string::String,
}
impl ::prost::Name for LikeButton {
    const NAME: &'static str = "LikeButton";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.LikeButton".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.LikeButton".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mask {
    ///
    #[prost(message, optional, tag = "1")]
    pub avatar: ::core::option::Option<Avatar>,
    ///
    #[prost(message, optional, tag = "2")]
    pub button: ::core::option::Option<Button>,
}
impl ::prost::Name for Mask {
    const NAME: &'static str = "Mask";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.Mask".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.Mask".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MiddleCoverV2 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(int32, tag = "2")]
    pub ratio: i32,
    ///
    #[prost(string, tag = "3")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub badge: ::prost::alloc::string::String,
}
impl ::prost::Name for MiddleCoverV2 {
    const NAME: &'static str = "MiddleCoverV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.MiddleCoverV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.MiddleCoverV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MiddleCoverV3 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub desc1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub desc2: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "4")]
    pub cover_badge_style: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for MiddleCoverV3 {
    const NAME: &'static str = "MiddleCoverV3";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.MiddleCoverV3".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.MiddleCoverV3".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MultiItem {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub more_uri: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub more_text: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "4")]
    pub items: ::prost::alloc::vec::Vec<DoubleCards>,
}
impl ::prost::Name for MultiItem {
    const NAME: &'static str = "MultiItem";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.MultiItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.MultiItem".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnePicV2 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(int32, tag = "2")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "3")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub cover_right_text: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "5")]
    pub cover_right_icon: i32,
    ///
    #[prost(string, tag = "6")]
    pub cover_right_background_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub badge: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "8")]
    pub rcmd_reason: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "9")]
    pub avatar: ::core::option::Option<Avatar>,
    ///
    #[prost(message, optional, tag = "10")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for OnePicV2 {
    const NAME: &'static str = "OnePicV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.OnePicV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.OnePicV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnePicV3 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "3")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "4")]
    pub cover_right_text: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "5")]
    pub cover_right_icon: i32,
    ///
    #[prost(string, tag = "6")]
    pub cover_right_background_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub badge: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "8")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for OnePicV3 {
    const NAME: &'static str = "OnePicV3";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.OnePicV3".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.OnePicV3".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PanelMeta {
    ///
    #[prost(int32, tag = "1")]
    pub panel_type: i32,
    ///
    #[prost(string, tag = "2")]
    pub share_origin: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub share_id: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "4")]
    pub functional_buttons: ::prost::alloc::vec::Vec<FunctionalButton>,
}
impl ::prost::Name for PanelMeta {
    const NAME: &'static str = "PanelMeta";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.PanelMeta".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.PanelMeta".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerArgs {
    ///
    #[prost(int32, tag = "1")]
    pub is_live: i32,
    ///
    #[prost(int64, tag = "2")]
    pub aid: i64,
    ///
    #[prost(int64, tag = "3")]
    pub cid: i64,
    ///
    #[prost(int32, tag = "4")]
    pub sub_type: i32,
    ///
    #[prost(int64, tag = "5")]
    pub room_id: i64,
    ///
    #[prost(int64, tag = "7")]
    pub ep_id: i64,
    ///
    #[prost(int32, tag = "8")]
    pub is_preview: i32,
    ///
    #[prost(string, tag = "9")]
    pub r#type: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "10")]
    pub duration: i64,
    ///
    #[prost(int64, tag = "11")]
    pub season_id: i64,
}
impl ::prost::Name for PlayerArgs {
    const NAME: &'static str = "PlayerArgs";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.PlayerArgs".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.PlayerArgs".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PopularTopEntrance {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<EntranceItem>,
}
impl ::prost::Name for PopularTopEntrance {
    const NAME: &'static str = "PopularTopEntrance";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.PopularTopEntrance".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.PopularTopEntrance".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RcmdOneItem {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(message, optional, tag = "2")]
    pub top_rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "3")]
    pub item: ::core::option::Option<SmallCoverRcmdItem>,
}
impl ::prost::Name for RcmdOneItem {
    const NAME: &'static str = "RcmdOneItem";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.RcmdOneItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.RcmdOneItem".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReasonStyle {
    ///
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub text_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub bg_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub border_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub icon_url: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub text_color_night: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub bg_color_night: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "8")]
    pub border_color_night: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "9")]
    pub icon_night_url: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "10")]
    pub bg_style: i32,
    ///
    #[prost(string, tag = "11")]
    pub uri: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "12")]
    pub icon_bg_url: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "13")]
    pub event: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "14")]
    pub event_v2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "15")]
    pub right_icon_type: i32,
    ///
    #[prost(string, tag = "16")]
    pub left_icon_type: ::prost::alloc::string::String,
}
impl ::prost::Name for ReasonStyle {
    const NAME: &'static str = "ReasonStyle";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ReasonStyle".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ReasonStyle".into()
    }
}
///
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Relation {
    ///
    #[prost(int32, tag = "1")]
    pub status: i32,
    ///
    #[prost(int32, tag = "2")]
    pub is_follow: i32,
    ///
    #[prost(int32, tag = "3")]
    pub is_followed: i32,
}
impl ::prost::Name for Relation {
    const NAME: &'static str = "Relation";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.Relation".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.Relation".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SharePlane {
    ///
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub share_subtitle: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub cover: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "5")]
    pub aid: i64,
    ///
    #[prost(string, tag = "6")]
    pub bvid: ::prost::alloc::string::String,
    ///
    #[prost(map = "string, bool", tag = "7")]
    pub share_to: ::std::collections::HashMap<::prost::alloc::string::String, bool>,
    ///
    #[prost(string, tag = "8")]
    pub author: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "9")]
    pub author_id: i64,
    ///
    #[prost(string, tag = "10")]
    pub short_link: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "11")]
    pub play_number: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "12")]
    pub first_cid: i64,
}
impl ::prost::Name for SharePlane {
    const NAME: &'static str = "SharePlane";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SharePlane".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SharePlane".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallChannelSpecial {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub bg_cover: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub desc1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub desc2: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub badge: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "6")]
    pub rcmd_reason_style2: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for SmallChannelSpecial {
    const NAME: &'static str = "SmallChannelSpecial";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallChannelSpecial".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallChannelSpecial".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallCoverConvergeV2 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "3")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "4")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "5")]
    pub cover_left_icon2: i32,
    ///
    #[prost(string, tag = "6")]
    pub cover_right_text: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub cover_right_top_text: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "8")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "9")]
    pub rcmd_reason_style_v2: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for SmallCoverConvergeV2 {
    const NAME: &'static str = "SmallCoverConvergeV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallCoverConvergeV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallCoverConvergeV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallCoverRcmdItem {
    ///
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub cover: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub uri: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub param: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub goto: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub cover_right_text1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub right_desc1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "8")]
    pub right_desc2: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "9")]
    pub cover_gif: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "10")]
    pub right_icon1: i32,
    ///
    #[prost(int32, tag = "11")]
    pub right_icon2: i32,
    ///
    #[prost(string, tag = "12")]
    pub cover_right_text_content_description: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "13")]
    pub right_desc1_content_description: ::prost::alloc::string::String,
}
impl ::prost::Name for SmallCoverRcmdItem {
    const NAME: &'static str = "SmallCoverRcmdItem";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallCoverRcmdItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallCoverRcmdItem".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallCoverV2 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_gif: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "3")]
    pub cover_blur: i32,
    ///
    #[prost(string, tag = "4")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "5")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "6")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "7")]
    pub cover_left_icon2: i32,
    ///
    #[prost(string, tag = "8")]
    pub cover_right_text: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "9")]
    pub cover_right_icon: i32,
    ///
    #[prost(string, tag = "10")]
    pub cover_right_background_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "11")]
    pub subtitle: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "12")]
    pub badge: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "13")]
    pub rcmd_reason: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "14")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "15")]
    pub avatar: ::core::option::Option<Avatar>,
    ///
    #[prost(int32, tag = "16")]
    pub official_icon: i32,
    ///
    #[prost(int32, tag = "17")]
    pub can_play: i32,
    ///
    #[prost(message, optional, tag = "18")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "19")]
    pub rcmd_reason_style_v2: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "20")]
    pub like_button: ::core::option::Option<LikeButton>,
}
impl ::prost::Name for SmallCoverV2 {
    const NAME: &'static str = "SmallCoverV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallCoverV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallCoverV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallCoverV3 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(message, optional, tag = "2")]
    pub avatar: ::core::option::Option<Avatar>,
    ///
    #[prost(string, tag = "3")]
    pub cover_left_text: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "4")]
    pub cover_right_button: ::core::option::Option<Button>,
    ///
    #[prost(string, tag = "5")]
    pub rcmd_reason: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "7")]
    pub official_icon: i32,
    ///
    #[prost(int32, tag = "8")]
    pub can_play: i32,
    ///
    #[prost(message, optional, tag = "9")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for SmallCoverV3 {
    const NAME: &'static str = "SmallCoverV3";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallCoverV3".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallCoverV3".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallCoverV4 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_badge: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub title_right_text: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "5")]
    pub title_right_pic: i32,
}
impl ::prost::Name for SmallCoverV4 {
    const NAME: &'static str = "SmallCoverV4";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallCoverV4".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallCoverV4".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallCoverV5 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_gif: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "3")]
    pub up: ::core::option::Option<Up>,
    ///
    #[prost(string, tag = "4")]
    pub cover_right_text1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub right_desc1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub right_desc2: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "7")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "8")]
    pub hotword_entrance: ::core::option::Option<HotwordEntrance>,
    ///
    #[prost(message, optional, tag = "9")]
    pub corner_mark_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(int32, tag = "10")]
    pub right_icon1: i32,
    ///
    #[prost(int32, tag = "11")]
    pub right_icon2: i32,
    ///
    #[prost(message, optional, tag = "12")]
    pub left_corner_mark_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(string, tag = "13")]
    pub cover_right_text_content_description: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "14")]
    pub right_desc1_content_description: ::prost::alloc::string::String,
}
impl ::prost::Name for SmallCoverV5 {
    const NAME: &'static str = "SmallCoverV5";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallCoverV5".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallCoverV5".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallCoverV5Ad {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_gif: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "3")]
    pub up: ::core::option::Option<Up>,
    ///
    #[prost(string, tag = "4")]
    pub cover_right_text1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub right_desc1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub right_desc2: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "7")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "8")]
    pub hotword_entrance: ::core::option::Option<HotwordEntrance>,
    ///
    #[prost(message, optional, tag = "9")]
    pub corner_mark_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(int32, tag = "10")]
    pub right_icon1: i32,
    ///
    #[prost(int32, tag = "11")]
    pub right_icon2: i32,
    ///
    #[prost(message, optional, tag = "12")]
    pub left_corner_mark_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(string, tag = "13")]
    pub cover_right_text_content_description: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "14")]
    pub right_desc1_content_description: ::prost::alloc::string::String,
}
impl ::prost::Name for SmallCoverV5Ad {
    const NAME: &'static str = "SmallCoverV5Ad";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallCoverV5Ad".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallCoverV5Ad".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallCoverV7 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub desc: ::prost::alloc::string::String,
}
impl ::prost::Name for SmallCoverV7 {
    const NAME: &'static str = "SmallCoverV7";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallCoverV7".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallCoverV7".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallCoverV9 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "3")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "4")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "5")]
    pub cover_left_icon2: i32,
    ///
    #[prost(string, tag = "6")]
    pub cover_right_text: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "7")]
    pub cover_right_icon: i32,
    ///
    #[prost(int32, tag = "8")]
    pub can_play: i32,
    ///
    #[prost(message, optional, tag = "9")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "10")]
    pub up: ::core::option::Option<Up>,
    ///
    #[prost(message, optional, tag = "11")]
    pub left_cover_badge_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, optional, tag = "12")]
    pub left_bottom_rcmd_reason_style: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for SmallCoverV9 {
    const NAME: &'static str = "SmallCoverV9";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.SmallCoverV9".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.SmallCoverV9".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreeItemAllV2 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(message, optional, tag = "2")]
    pub top_rcmd_reason_style: ::core::option::Option<ReasonStyle>,
    ///
    #[prost(message, repeated, tag = "3")]
    pub item: ::prost::alloc::vec::Vec<TwoItemHv1Item>,
}
impl ::prost::Name for ThreeItemAllV2 {
    const NAME: &'static str = "ThreeItemAllV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreeItemAllV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreeItemAllV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreeItemV1 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(int32, tag = "2")]
    pub title_icon: i32,
    ///
    #[prost(string, tag = "3")]
    pub more_uri: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub more_text: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "5")]
    pub items: ::prost::alloc::vec::Vec<ThreeItemV1Item>,
}
impl ::prost::Name for ThreeItemV1 {
    const NAME: &'static str = "ThreeItemV1";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreeItemV1".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreeItemV1".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreeItemV1Item {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub cover_left_text: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "3")]
    pub cover_left_icon: i32,
    ///
    #[prost(string, tag = "4")]
    pub desc1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub desc2: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub badge: ::prost::alloc::string::String,
}
impl ::prost::Name for ThreeItemV1Item {
    const NAME: &'static str = "ThreeItemV1Item";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreeItemV1Item".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreeItemV1Item".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreeItemV2 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(int32, tag = "2")]
    pub title_icon: i32,
    ///
    #[prost(string, tag = "3")]
    pub more_uri: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub more_text: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "5")]
    pub items: ::prost::alloc::vec::Vec<ThreeItemV2Item>,
}
impl ::prost::Name for ThreeItemV2 {
    const NAME: &'static str = "ThreeItemV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreeItemV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreeItemV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreeItemV2Item {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(int32, tag = "2")]
    pub cover_left_icon: i32,
    ///
    #[prost(string, tag = "3")]
    pub desc_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "4")]
    pub desc_icon1: i32,
    ///
    #[prost(string, tag = "5")]
    pub desc_text2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "6")]
    pub desc_icon2: i32,
    ///
    #[prost(string, tag = "7")]
    pub badge: ::prost::alloc::string::String,
}
impl ::prost::Name for ThreeItemV2Item {
    const NAME: &'static str = "ThreeItemV2Item";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreeItemV2Item".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreeItemV2Item".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreePicV2 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub left_cover: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub right_cover1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub right_cover2: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "6")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "7")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "8")]
    pub cover_left_icon2: i32,
    ///
    #[prost(string, tag = "9")]
    pub cover_right_text: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "10")]
    pub cover_right_icon: i32,
    ///
    #[prost(string, tag = "11")]
    pub cover_right_background_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "12")]
    pub badge: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "13")]
    pub rcmd_reason: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "14")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "15")]
    pub avatar: ::core::option::Option<Avatar>,
    ///
    #[prost(message, optional, tag = "16")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for ThreePicV2 {
    const NAME: &'static str = "ThreePicV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreePicV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreePicV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreePicV3 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub left_cover: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub right_cover1: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub right_cover2: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "6")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "7")]
    pub cover_left_text2: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "8")]
    pub cover_left_icon2: i32,
    ///
    #[prost(string, tag = "9")]
    pub cover_right_text: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "10")]
    pub cover_right_icon: i32,
    ///
    #[prost(string, tag = "11")]
    pub cover_right_background_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "12")]
    pub badge: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "13")]
    pub rcmd_reason_style: ::core::option::Option<ReasonStyle>,
}
impl ::prost::Name for ThreePicV3 {
    const NAME: &'static str = "ThreePicV3";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreePicV3".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreePicV3".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreePoint {
    ///
    #[prost(message, repeated, tag = "1")]
    pub dislike_reasons: ::prost::alloc::vec::Vec<DislikeReason>,
    ///
    #[prost(message, repeated, tag = "2")]
    pub feedbacks: ::prost::alloc::vec::Vec<DislikeReason>,
    ///
    #[prost(int32, tag = "3")]
    pub watch_later: i32,
}
impl ::prost::Name for ThreePoint {
    const NAME: &'static str = "ThreePoint";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreePoint".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreePoint".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreePointV2 {
    ///
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub subtitle: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "3")]
    pub reasons: ::prost::alloc::vec::Vec<DislikeReason>,
    ///
    #[prost(string, tag = "4")]
    pub r#type: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "5")]
    pub id: i64,
}
impl ::prost::Name for ThreePointV2 {
    const NAME: &'static str = "ThreePointV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreePointV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreePointV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreePointV3 {
    ///
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub selected_title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub subtitle: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "4")]
    pub reasons: ::prost::alloc::vec::Vec<DislikeReason>,
    ///
    #[prost(string, tag = "5")]
    pub r#type: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "6")]
    pub id: i64,
    ///
    #[prost(int32, tag = "7")]
    pub selected: i32,
    ///
    #[prost(string, tag = "8")]
    pub icon: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "9")]
    pub selected_icon: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "10")]
    pub url: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "11")]
    pub default_id: i32,
}
impl ::prost::Name for ThreePointV3 {
    const NAME: &'static str = "ThreePointV3";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreePointV3".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreePointV3".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreePointV4 {
    ///
    #[prost(message, optional, tag = "1")]
    pub share_plane: ::core::option::Option<SharePlane>,
    ///
    #[prost(message, optional, tag = "2")]
    pub watch_later: ::core::option::Option<WatchLater>,
}
impl ::prost::Name for ThreePointV4 {
    const NAME: &'static str = "ThreePointV4";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.ThreePointV4".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.ThreePointV4".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicButton {
    ///
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub jump_uri: ::prost::alloc::string::String,
    ///
    #[prost(bool, tag = "3")]
    pub red_dot: bool,
}
impl ::prost::Name for TopicButton {
    const NAME: &'static str = "TopicButton";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.TopicButton".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.TopicButton".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicList {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub title_icon: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "4")]
    pub more_button: ::core::option::Option<TopicButton>,
    ///
    #[prost(message, repeated, tag = "5")]
    pub topic_list_item: ::prost::alloc::vec::Vec<TopicListItem>,
}
impl ::prost::Name for TopicList {
    const NAME: &'static str = "TopicList";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.TopicList".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.TopicList".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicListItem {
    ///
    #[prost(string, tag = "1")]
    pub icon: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub icon_title: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "3")]
    pub topic_id: i64,
    ///
    #[prost(string, tag = "4")]
    pub topic_name: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub url: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "6")]
    pub up_mid: i64,
    ///
    #[prost(int64, tag = "7")]
    pub position: i64,
}
impl ::prost::Name for TopicListItem {
    const NAME: &'static str = "TopicListItem";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.TopicListItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.TopicListItem".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TwoItemHv1Item {
    ///
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub cover: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub uri: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub param: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "5")]
    pub args: ::core::option::Option<Args>,
    ///
    #[prost(string, tag = "6")]
    pub goto: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "8")]
    pub cover_left_icon1: i32,
    ///
    #[prost(string, tag = "9")]
    pub cover_right_text: ::prost::alloc::string::String,
}
impl ::prost::Name for TwoItemHv1Item {
    const NAME: &'static str = "TwoItemHV1Item";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.TwoItemHV1Item".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.TwoItemHV1Item".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TwoItemV2 {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<TwoItemV2Item>,
}
impl ::prost::Name for TwoItemV2 {
    const NAME: &'static str = "TwoItemV2";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.TwoItemV2".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.TwoItemV2".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TwoItemV2Item {
    ///
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<Base>,
    ///
    #[prost(string, tag = "2")]
    pub badge: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub cover_left_text1: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "4")]
    pub cover_left_icon1: i32,
}
impl ::prost::Name for TwoItemV2Item {
    const NAME: &'static str = "TwoItemV2Item";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.TwoItemV2Item".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.TwoItemV2Item".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Up {
    ///
    #[prost(int64, tag = "1")]
    pub id: i64,
    ///
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub desc: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "4")]
    pub avatar: ::core::option::Option<Avatar>,
    ///
    #[prost(int32, tag = "5")]
    pub official_icon: i32,
    ///
    #[prost(message, optional, tag = "6")]
    pub desc_button: ::core::option::Option<Button>,
    ///
    #[prost(string, tag = "7")]
    pub cooperation: ::prost::alloc::string::String,
}
impl ::prost::Name for Up {
    const NAME: &'static str = "Up";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.Up".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.Up".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpArgs {
    ///
    #[prost(int64, tag = "1")]
    pub up_id: i64,
    ///
    #[prost(string, tag = "2")]
    pub up_name: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub up_face: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "4")]
    pub selected: i64,
}
impl ::prost::Name for UpArgs {
    const NAME: &'static str = "UpArgs";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.UpArgs".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.UpArgs".into()
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchLater {
    ///
    #[prost(int64, tag = "1")]
    pub aid: i64,
    ///
    #[prost(string, tag = "2")]
    pub bvid: ::prost::alloc::string::String,
}
impl ::prost::Name for WatchLater {
    const NAME: &'static str = "WatchLater";
    const PACKAGE: &'static str = "bilibili.app.card.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.app.card.v1.WatchLater".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.app.card.v1.WatchLater".into()
    }
}
