// This file is @generated by prost-build.
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GoldRankBroadcast {
    ///
    #[prost(string, tag = "1")]
    pub rank_type: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "2")]
    pub list: ::prost::alloc::vec::Vec<gold_rank_broadcast::GoldRankBroadcastItem>,
    ///
    #[prost(message, repeated, tag = "3")]
    pub online_list: ::prost::alloc::vec::Vec<
        gold_rank_broadcast::GoldRankBroadcastItem,
    >,
}
/// Nested message and enum types in `GoldRankBroadcast`.
pub mod gold_rank_broadcast {
    ///
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct GoldRankBroadcastItem {
        ///
        #[prost(int64, tag = "1")]
        pub uid: i64,
        ///
        #[prost(string, tag = "2")]
        pub face: ::prost::alloc::string::String,
        ///
        #[prost(string, tag = "3")]
        pub score: ::prost::alloc::string::String,
        ///
        #[prost(string, tag = "4")]
        pub uname: ::prost::alloc::string::String,
        ///
        #[prost(int64, tag = "5")]
        pub rank: i64,
        ///
        #[prost(int64, tag = "6")]
        pub guard_level: i64,
        ///
        #[prost(bool, tag = "7")]
        pub is_mystery: bool,
        ///
        #[prost(message, optional, tag = "8")]
        pub uinfo: ::core::option::Option<
            super::super::super::component::common_model::user_dagw::UserInfo,
        >,
    }
    impl ::prost::Name for GoldRankBroadcastItem {
        const NAME: &'static str = "GoldRankBroadcastItem";
        const PACKAGE: &'static str = "bilibili.live.rankdb.v1";
        fn full_name() -> ::prost::alloc::string::String {
            "bilibili.live.rankdb.v1.GoldRankBroadcast.GoldRankBroadcastItem".into()
        }
        fn type_url() -> ::prost::alloc::string::String {
            "/bilibili.live.rankdb.v1.GoldRankBroadcast.GoldRankBroadcastItem".into()
        }
    }
}
impl ::prost::Name for GoldRankBroadcast {
    const NAME: &'static str = "GoldRankBroadcast";
    const PACKAGE: &'static str = "bilibili.live.rankdb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "bilibili.live.rankdb.v1.GoldRankBroadcast".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bilibili.live.rankdb.v1.GoldRankBroadcast".into()
    }
}
