// This file is @generated by prost-build.
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Locale {
    ///
    #[prost(message, optional, tag = "1")]
    pub c_locale: ::core::option::Option<LocaleIds>,
    ///
    #[prost(message, optional, tag = "2")]
    pub s_locale: ::core::option::Option<LocaleIds>,
    ///
    #[prost(string, tag = "3")]
    pub sim_code: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub timezone: ::prost::alloc::string::String,
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocaleIds {
    ///
    #[prost(string, tag = "1")]
    pub language: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub script: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub region: ::prost::alloc::string::String,
}
