// This file is @generated by prost-build.
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InternalDeviceConfig {
    ///
    #[prost(message, optional, tag = "1")]
    pub fts: ::core::option::Option<super::super::Int64Value>,
}
